<a href="https://colab.research.google.com/github/sushii-00/DanielBourke_DL_Course/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook. we're going to cover some of the most fundamental concepts of tensors using tensorflow.

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular python functions)
* Using GPUs (or TPUs) with tensorflow
* Exercises to try 


# Introduction to tensors 

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)  

2.4.1


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimensions of a tensor(ndim stands for the number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
 # check the dimension of our vector
 vector.ndim

1

In [ ]:
# Create a matrix (has more than 1 dimensions)
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
matrix1 = tf.constant([[10,7,3],      #shape is rows,columns
                      [3,7,10]])
matrix1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  7,  3],
       [ 3,  7, 10]], dtype=int32)>

In [ ]:
matrix1.ndim

2

In [ ]:
another_matrix = tf.constant([[10.,7.],     #the default data type is 32, however we can manipulate the datatype, which is shown in the next cell.
                             [3.,2.],
                             [4.,6.]])

In [ ]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 4.,  6.]], dtype=float32)>

In [ ]:
another_matrix1 = tf.constant([[10.,7.],     
                             [3.,2.],
                             [4.,6.]],dtype=tf.float16)
another_matrix1

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 4.,  6.]], dtype=float16)>

In [ ]:
# The above method will let our floating point numbers take less memory space because they are less precise than float32

In [ ]:
another_matrix1.ndim   #dimensions is how many elements are there inthe shape

2

In [ ]:
#let's create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor  

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
#all of these are tensors

what we've created so far:
* scalar:  a single number (0d tensor)
* Vector: a number with direction(eg. wind speed and direction)(1d tensor)
* Matrix: a 2- dimensional array of numbers (2d tensor)
*Tensor: an n-dimnesional array of numbers(when n can be any number, 0 dimensional tensor is a scalar, a 1 dimensional tensor is a vector)

### tf.variable

In [ ]:
#Create the same tensor with tf.Variable() as above. 

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

##to change one of the elements in our changeable_tensor


In [ ]:
changeable_tensor[0]


<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
changeable_tensor[0].assign(11)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([11,  7], dtype=int32)>

WE CAN'T CHANGE THE unchangeable_tensor because we made it using tf.constant.
So the tensors made using tf.variable are mutable and those made using tf.constant are unmutable.

You can also (although you likely rarely will, because often, when working with data, tensors are created for you automatically) create tensors using tf.Variable().

##Creating random tensors

Random tensors are tensors of arbitrary size filled with random numbers.

In [ ]:
 # Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1,random_2, random_1 == random_2 

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## how about we change the seed in random_2 ?
the results aren't the same.

In [ ]:
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))
random_1,random_2, random_1 == random_2 

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

anyway, back to the same random tensors

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1,random_2, random_1 == random_2 

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### shuffle the order of elements in a tensor.

In [ ]:
## shuffle a tensor(valuable whenyou want to shuffle your data so the inherent order doesnt affect learning)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]]) 


Randomly shuffles a tensor along its first dimension. : tf.random.shuffle
* we need to shuffle our information in order to make our model study information about all sorts of groups present in the data.
* SHUFFLE OUR NON- SHUFFLED TENSOR:


In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

shuffling from the tensorflow documentation

* see what is seed and shuffling

In [ ]:
print(tf.random.uniform([1])) #generates A1
print(tf.random.uniform([1])) #generates A2

tf.Tensor([0.6645621], shape=(1,), dtype=float32)
tf.Tensor([0.68789124], shape=(1,), dtype=float32)


In [ ]:
print(tf.random.uniform([1]))  #generates A3
print(tf.random.uniform([1]))  #generates A4

tf.Tensor([0.7413678], shape=(1,), dtype=float32)
tf.Tensor([0.7402308], shape=(1,), dtype=float32)


   it looks like if we want our shuffled tensors to be in the same order, we've got to use the global levele random seed as well as the perational level random seed:

In [ ]:
# so,

tf.random.set_seed(42)  #global level random seed
tf.random.shuffle(not_shuffled, seed =42) #operational level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

the above code produces : "REPRODUCABLE RANDOMNESS. WHICH IS WHY THIS IS ALSO PSUEDO RANDOM"

### OTHER WAYS TO MAKE TENSORS

In [ ]:
#USING NUMPY
#tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([4,3])
# we could also do this as:
# tf.zeros(shape=(3,4))

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### The main diffenence btw numpy array and tensorflow tensors is that tensors can be run on a GPU , therefore, faster computing

In [ ]:
#you can also turn numpy arrays into tensorflow tensors
import numpy as np
numpy_A=np.arange(1,25, dtype=np.int32) #creating a numpy array btw 1 and 25
numpy_A
    

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

TO CONVERT NUMPY ARRAY INTO A TENSOR

In [ ]:
A = tf.constant(numpy_A)

In [ ]:
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
B = tf.constant(numpy_A, shape=(2,3,4))
C = tf.constant(numpy_A, shape= (2,12))
A,B,C

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>)

### GETTING INFORMATION FROM TENSORS
when dealing w tensors you probably want to be aware of the foll attributes
* Shape             : tensor.shape
* Rank              : tensor.ndim
* Axis or dimension : tensor[0], tensor[:1]
* Size : tf.size(tensor)

In [ ]:
#create a rank4 tensor
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor[0,0]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim , tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element:" ,rank_4_tensor.dtype)
print("No of elements(rank):" ,rank_4_tensor.ndim)
print("shape of the tensor:" ,rank_4_tensor.shape)
print("elements along the 0 axis:", rank_4_tensor.shape[0]) #2
print("elements along the last axis", rank_4_tensor.shape[-1]) #5
print("total number of elements in our tensor:", tf.size(rank_4_tensor))
#tf.Tensor(120, shape=(), dtype=int32) : will be the output. 
#if you want to shorten the output just add numpy() in the end.
print("total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())


Datatype of every element: <dtype: 'float32'>
No of elements(rank): 4
shape of the tensor: (2, 3, 4, 5)
elements along the 0 axis: 2
elements along the last axis 5
total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
total number of elements in our tensor: 120


### indexing tensors
tensors can be indexed just lije python lists

In [ ]:
#get the first 2 elements of each dimension
some_list=[1,2,3,4]
some_list[:2]

[1, 2]

In [ ]:
#get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1, :1, : ,:1] #except for the 2nd last dimension

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
#adding an extra dimension at the end of a tensor

#Create a rank 2 tensor(2 dimensions)
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor, rank_2_tensor.shape, rank_2_tensor.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>, TensorShape([2, 2]), 2)

In [ ]:
# get the last item of each row of the tensor just created.
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
#add in an extra dimenision, but keeping the exact same info that is there in the rank 2 tensor we just made.
rank_3_tensor = rank_2_tensor[..., tf.newaxis] #... signify to add a new axis after all the the axes
rank_3_tensor 

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#ALTERNATIVE TO tf.newaxis

tf.expand_dims(rank_2_tensor, axis = -1) #here '-1' means expand the final axis 

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#expand the 0th axis

tf.expand_dims(rank_2_tensor, axis=0)   #:0 adds an extra dimension in the beginning

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [ ]:
 rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

#### MANIPULATING TENSORS(TENSOR OPERATIONS)

Finding patterns in tensors (numberical representation of data) requires manipulating them.
Again, when building models in TensorFlow, much of this pattern discovery is done for you.


In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
#original tensor
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
#subtraction
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

You can also use the equivalent TensorFlow function. Using the TensorFlow function (where possible) has the advantage of being sped up later down the line when running as part of a TensorFlow graph.


In [ ]:
#use the tensorflow function equivalent of the '*' (multiply) operator
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# The original tensor is still unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

**Matrix mutliplication**

One of the most common operations in machine learning algorithms is matrix multiplication.

TensorFlow implements this matrix multiplication functionality in the tf.matmul() method.
The main two rules for matrix multiplication to remember are:
1. The inner dimensions must match:
* (3, 5) @ (3, 5) won't work
* (5, 3) @ (3, 5) will work
* (3, 5) @ (5, 3) will work
2. The resulting matrix has the shape of the outer dimensions:
* (5, 3) @ (3, 5) -> (5, 5)
* (3, 5) @ (5, 3) -> (3, 3)
🔑 Note: '@' in Python is the symbol for matrix multiplication.

In [ ]:
#matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#u can even do matruix multiplication using a python operator.
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

**while performing matrix multiplication we might need the following information**

* transpose of matrices
* reshaping vectors

the important thing that we need to remember is that, both of these functions ARE NOT THE SAME.

This can be explained by the default behaviour of each method:
* tf.reshape() - change the shape of the given tensor (first) and then insert values in order they appear (in our case, 7, 8, 9, 10, 11, 12).
* tf.transpose() - swap the order of the axes, by default the last axis becomes the first, however the order can be changed using the perm parameter.

So which should you use?

Again, most of the time these operations (when they need to be run, such as during the training a neural network, will be implemented for you).
But generally, whenever performing a matrix multiplication and the shapes of two matrices don't line up, you will transpose (not reshape) one of them in order to line them up.

In [ ]:
Y = tf.constant([
                 [1,2],
                 [3,4],
                 [5,6]])

In [ ]:
# Check values of Y, reshape Y and tranposed Y
print("Normal Y:")
print(Y, "\n") # "\n" for newline

print("tensor Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("tensor Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32) 

tensor Y reshaped to (2, 3):
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32) 

tensor Y transposed:
tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)


### changing the datatype of a tensor

In [ ]:
# Create a new tensor with default datatype(float32)
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [ ]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [ ]:
tf.__version__

'2.4.1'

Change from float32 to float16: Reduced Precision
* Mixed precision is the use of both 16-bit and 32-bit floating point typesin a model during training to make it run faster and use less memory.
* By keeping certain parts of the model in the 32 bit type for numeric stability, the model will have a lower step time and traing equally as well in terms of the evaluation metrics such as accuracy.
* Today, most models use the float32 dtype, which takes 32 bits of memory. However, there are two lower- precision dtypes, float16 and bfloat16, each which take 16 bits of memory instead. Modern accelarators can run operators faster in the 16 bit dtypes as they have specialised hardware to run 16 but computations and 16 bit dtypes can be read from memeory faster.



In [ ]:
D = tf.cast(B, dtype= tf.float16) #we are type casting the floating numbers
D,D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# change from int 32 to float32
E = tf.cast(C, dtype = tf.float32)
C.dtype,E,E.dtype

(tf.int32,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

In [ ]:
print(E)
print(C)

tf.Tensor([ 7. 10.], shape=(2,), dtype=float32)
tf.Tensor([ 7 10], shape=(2,), dtype=int32)


### AGGREGATING TENSORS

* AGGREGARTING = condensing them from multiple values down to a smaller amount of values.

In [ ]:
# gete the absolute values
D = tf.constant([-7,-10])
D
tf.abs(D) 
# in the o/p we have the absolute values of the values inside the tensor
# use comm+sft+space to see the docstring of all these functions


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets' go through the foll forms of aggregation
* Get the miniimum
* get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
#start by creating a random tensor with values bw 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100, size =50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([20, 79, 65, 28, 93, 18, 89, 78, 18, 27, 64,  2, 91, 34, 49,  6, 99,
       41, 95, 91, 21, 97, 20, 47, 71, 29, 42, 62, 70, 48, 40, 22, 30,  1,
       89, 52, 60,  3, 75, 41, 38, 59, 22, 86, 57, 77, 70, 63,  2, 20])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
#get the max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
#find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [ ]:
#find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2501>

**EXERCISE**

Find the variance and standard deviation of the tensor E, using the methods shown above

In [ ]:
# Variance : Var(X) = Σ ( Xi - X )2 / N = Σ xi2 / N
E_dash = tf.reduce_mean(E)-E
E_dash

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 30, -29, -15,  22, -43,  32, -39, -28,  32,  23, -14,  48, -41,
        16,   1,  44, -49,   9, -45, -41,  29, -47,  30,   3, -21,  21,
         8, -12, -20,   2,  10,  28,  20,  49, -39,  -2, -10,  47, -25,
         9,  12,  -9,  28, -36,  -7, -27, -20, -13,  48,  30])>

In [ ]:
E_dash2 = tf.math.square(E_dash)
E_dash2

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 900,  841,  225,  484, 1849, 1024, 1521,  784, 1024,  529,  196,
       2304, 1681,  256,    1, 1936, 2401,   81, 2025, 1681,  841, 2209,
        900,    9,  441,  441,   64,  144,  400,    4,  100,  784,  400,
       2401, 1521,    4,  100, 2209,  625,   81,  144,   81,  784, 1296,
         49,  729,  400,  169, 2304,  900])>

In [ ]:
tf.reduce_sum(E_dash2) 

<tf.Tensor: shape=(), dtype=int64, numpy=42277>

In [ ]:
var = tf.divide(tf.reduce_sum(E_dash2),50)
var

<tf.Tensor: shape=(), dtype=float64, numpy=845.54>

In [ ]:
# Deviation :  square root of variance
std_dev = tf.math.sqrt(var)
std_dev

<tf.Tensor: shape=(), dtype=float64, numpy=29.078170506412537>

In [ ]:
 # we could also used an inbuilt function to fine the variance
 import tensorflow_probability as tfp
 tfp.stats.variance(E)

 #tf.math.reduce_variance(tf.cast(E, dtype = tf.float32)) : would also work

<tf.Tensor: shape=(), dtype=int64, numpy=845>

In [ ]:
#find the standard deviation
#tf.math.reduce_std(E). ERROR : Input must be either real or complex
#WE WOULD HAVE TO TYPECAST IT.
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.078163>

###Find a positional maximum and minimum

In [ ]:
# Create a new tensor to find the positional maximum and minimum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(F)    #42nd number 

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### SQUEEZING A TENSOR

tf.squeeze(G): Removes dimensions of size 1 from the shape of a tensor.

In [ ]:
#CREATE A Tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
 G_squeezed = tf.squeeze(G) #Removes dimensions of size 1 from the shape of a tensor.
 G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### ONE-HOT ENCODING

* IT IS A FORM OF NUMERICAL ENCODING
* IF WE PROVIDE LETTERS TO A COMPUTER, IT WON'T BE ABLE TO PERFORM NUMERICAL OPERATIONS ONIT. THEREFORE WE WILL HAVE TO ONE-HOT ENCODE SUCH CASES

In [ ]:
 # TO PERFORM ONE HOT ENCODING we need to create a random list
 some_list = [0,1,2,3] #could be red, green, blue, purple

 #one-hot encode our list of indices
 tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="yo i love deep learning", off_value="I ALSOLIKE TO DANCE")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo i love deep learning', b'I ALSOLIKE TO DANCE',
        b'I ALSOLIKE TO DANCE', b'I ALSOLIKE TO DANCE'],
       [b'I ALSOLIKE TO DANCE', b'yo i love deep learning',
        b'I ALSOLIKE TO DANCE', b'I ALSOLIKE TO DANCE'],
       [b'I ALSOLIKE TO DANCE', b'I ALSOLIKE TO DANCE',
        b'yo i love deep learning', b'I ALSOLIKE TO DANCE'],
       [b'I ALSOLIKE TO DANCE', b'I ALSOLIKE TO DANCE',
        b'I ALSOLIKE TO DANCE', b'yo i love deep learning']], dtype=object)>